name: sync opentelemetry-collector-contrib dependencies to main

on:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  sync-contrib-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '~1.15'
    - run: npm install @actions/exec semver
    - uses: actions/github-script@v3
      with:
        script: |
          const exec = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@actions/exec`)
          const semver = require(`${process.env.GITHUB_WORKSPACE}/node_modules/semver`)
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/auto-bump.js`)
          await script({github, core, context, exec, semver})
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update to opentelemetry-collector-contrib main.
        branch: actions/update-contrib
        delete-branch: true
        title: Update opentelemetry-collector-contrib to main
        base: main
        # TODO: Set to something useful.
        body: ''
